components/table/base/calculations.tsx, components/table/base/empty.tsx, components/table/base/header.tsx, components/table/base/html-table.tsx, components/table/base/styles.ts, components/table/common-views.tsx, components/table/demo/columnSort.md, components/table/demo/virtual.md, components/table/pipeline/features/__test__/treeMode.test.tsx, components/table/pipeline/features/__tests__/treeMode.test.tsx, components/table/pipeline/features/columnDrag.tsx, components/table/pipeline/features/contextMenu.tsx, components/table/pipeline/features/multiSelect.tsx, components/table/pipeline/features/rowDetail.tsx, components/table/pipeline/features/rowGrouping.tsx, components/table/pipeline/features/treeMode.tsx, components/table/pipeline/pipeline.ts, components/table/pivot/pivot-utils/convert-utils.tsx
feat: 
- 拖拽列顺序支持表格自动滚动功能
refactor: 
- 拖拽列顺序阻止点击事件冒泡,
- 表格行和单元格容易撞名的class
fix: 
- 右键菜单在页脚显示获取表体数据问题
=> sync: 表格功能同步及bug修复

components/table/pipeline/features/columnFilter.tsx, components/table/pipeline/features/filter/util.tsx, components/table/pipeline/features/multiSelect.tsx, components/table/pipeline/features/treeMode.tsx
1. 树形结构支持指定展开列&函数类型主键
2. 多选支持树形结构
3. 过滤支持树形结构
=> feat: 树形结构支持指定展开列&函数类型主键,过滤&多选适配树形结构

components/table/pipeline/features/columnDrag.tsx
=> fix: 优化拖拽过程中触发排序，修复偶现点击列头排序失效

components/table/base/styles.ts, components/table/demo/columnResize.md, components/table/pipeline/features/columnDrag.tsx, components/table/pipeline/features/columnFilter.tsx, components/table/pipeline/features/filter/DefaultFilterIcon.tsx, components/table/pipeline/features/filter/Filter.tsx, components/table/pipeline/features/filter/FilterPanel.tsx
=> 过滤功能优化，增加根据过滤状态自定义过滤图标接口

components/table/utils/mergeCellProps.ts
=> fix:修复单元格事件合并时参数传递有误问题

components/table/pipeline/pipeline.ts
=> fix: 表格宽度为0时不重新刷新表格

components/table/base/styles.ts, components/table/pipeline/features/columnFilter.tsx, components/table/pipeline/features/filter/Filter.tsx, components/table/pipeline/features/filter/FilterPanel.tsx
=> feat: 过滤弹出面板增加隐藏面板头参数hideFilterPopupHeader

components/table/pipeline/features/rangeSelection.tsx, components/table/pipeline/features/treeMode.tsx
=> fix:表格单元格可编辑时不允许范围选中全选 && 树形表格展开列过滤图标会换行显示

components/table/pipeline/features/rangeSelection.tsx
=> fix:表格范围选中全选时不能选中分组列

components/table/base/table.tsx, components/table/base/utils.tsx, components/table/utils/element.ts
=> fix: 页脚数据在空和有值切换时导致表格横向滚动条位置异常

components/table/base/styles.ts, components/table/pipeline/features/filter/Filter.tsx, components/table/pipeline/features/filter/FilterPanel.tsx, components/table/utils/keyCode.ts
=> feat: 支持按ESC键关闭过滤面板

components/table/base/table.tsx, components/table/pipeline/pipeline.ts
=> feat:表格暴露rowHeightManager属性

components/table/pipeline/features/colGroupExtendable.tsx
=> feat:添加分组列可伸缩特性中的图标可配置功能

components/table/pipeline/features/columnFilter.tsx, components/table/pipeline/features/filter/Filter.tsx
=> feat: 过滤面板按ESC键关闭的keydown事件可配置阻止该事件冒泡

components/table/pipeline/features/filter/Filter.tsx
=> fix: 过滤图标点击事件设置了阻止冒泡，在弹出面板的点击事件冒泡未被阻止

components/table/pipeline/features/columnFilter.tsx, components/table/pipeline/features/filter/Filter.tsx
=> feat: 增加过滤面板浮层渲染的父节点参数 getPopupParent

components/table/demo/rangeSelection.md, components/table/pipeline/features/rangeSelection.tsx
=> feat: 表格范围选中支持鼠标框选文本内容

components/table/pipeline/features/contextMenu.tsx
=> feat: 右键菜单支持设置菜单和子项的className

components/table/pipeline/features/filter/DefaultFilterContent.tsx
=> fix: 过滤面板输入框存在值，多次点击确认按钮值被嵌套多层数组

components/table/pipeline/features/autoFill.tsx, components/table/pipeline/features/columnResizeWidth.tsx, components/table/pipeline/features/multiSelect.tsx, components/table/pipeline/features/rangeSelection.tsx, components/table/pipeline/features/sort.tsx
=> perf: 表格性能优化，减少不必要的setState与数据遍历

components/table/pipeline/features/contextMenu.tsx
document.classList不存在 @xiaolinsq
=> fix: 开启右键菜单时，表头右键点击控制台提示为空异常

components/table/base/styles.ts, components/table/common-views.tsx
=> refactor: 调整右键菜单的样式及悬浮中性色默认色

components/table/demo/columnFlex.md, components/table/pipeline/features/autoFill.tsx, components/table/pipeline/features/columnResizeWidth.tsx, components/table/pipeline/pipeline.ts
@xiaolinsq 
[refactor: featureOptions 不会在表格重渲染清空其数据](https://github.com/kdcloudone/table/commit/3c49d61f31cc0cc80486a1265613d9923c3bcb23)[feat: 列增加flex属性，配置后的一个或多个列来填充表格中的整个可用空间](https://github.com/kdcloudone/table/commit/dbe42dcfec5ead5c5c3ce9346ef0a2cead153c28)
=> feat: 列增加flex属性，配置后的一个或多个列来填充表格中的整个可用空间

components/table/pipeline/features/autoFill.tsx
=> fix: 未开启列宽拖拽功能导致充满列宽度计算错误

components/table/pipeline/features/autoFill.tsx, components/table/pipeline/features/columnResizeWidth.tsx
=> feat: 列配置flex属性，拖拽列宽时，前面配置flex属性的列不要生效

components/table/demo/rangeSelection.md, components/table/index.md, components/table/pipeline/features/rangeSelection.tsx
=> feat:表格支持多范围框选功能

components/table/pipeline/features/multiSelect.tsx
=> perf: 多选行选择内部数据只保留一份，避免行数据过多时内存被握住

components/table/common-views.tsx, components/table/pipeline/features/columnResizeWidth.tsx
=> fix: 修复styled-components在IE下引用自定义标签报错的问题

components/table/base/helpers/TableDOMUtils.tsx, components/table/base/styles.ts, components/table/base/table.tsx
=> feat:[table] 修改滚动条位置以冻结列为起始点

components/table/pipeline/features/autoFill.tsx
=> fix: 未开启拖拽列宽功能时列宽充满异常

components/table/pipeline/features/rowDrag.tsx
=> fix:[table] 行拖拽支持禁止滚动条移动

components/table/pipeline/features/autoFill.tsx, components/table/pipeline/features/columnDrag.tsx, components/table/pipeline/features/rowDrag.tsx
=> fix:[table] 列拖拽结果不需要返回拖拽列

components/table/base/table.tsx
=> fix: 兼容react18严格模式下执行多次生命周期导致rxjs事件销毁异常

components/table/pipeline/features/columnFilter.tsx
=> fix: 列过滤Icon组件key相同

components/table/base/table.tsx
=> fix:表格没有出横向滚动条时不要显示底部多余的边框线

components/table/pipeline/features/treeMode.tsx, components/table/pipeline/pipeline.ts
=> feat:减少树形单据体的额外数据构建,解决性能问题

components/table/pipeline/features/treeMode.tsx
=> feat:树形单据体性能优化兼容 state 中无 openkeys 场景

components/table/base/styles.ts
=> fix: 修复低版本浏览器上tr元素使用after伪类时不兼容问题

components/table/pipeline/features/rangeSelection.tsx
=> fix: 拖动非定义列时不要触发滚动

components/table/base/table.tsx
=> feat:表格不可见的时候不需要处理滚动条

components/table/pipeline/features/rowDrag.tsx
=> fix: 修复行拖拽过程中滚轮滚动导致定位不准确的问题

components/table/base/table.tsx
=> fix:解决单据体横向滚动条右侧额外滚动条的问题

components/table/base/header.tsx
=> fix:修复分组列右冻结时分组头还会跟随滚动条滚动的问题

components/table/base/header.tsx, components/table/base/html-table.tsx, components/table/base/renderTemplates.tsx, components/table/base/styles.ts, components/table/base/table.tsx
=> fix: 修复表格纵向滚动条遮挡最后一个表格内容的问题

components/table/base/helpers/getRichVisibleRectsStream.ts
=> perf: props每次改变都会重新查找scrollParent元素导致回流

components/table/pipeline/features/columnFilter.tsx
=> fix:表格过滤时不输入任何值点过滤，过滤图标没有高亮

components/table/pipeline/features/columnDrag.tsx
=> fix: 列拖拽暴露开启拖拽接口

components/table/base/renderTemplates.tsx, components/table/base/styles.ts, components/table/base/table.tsx, components/table/base/utils.tsx, components/table/utils/browserType.tsx, components/table/utils/index.tsx, components/table/utils/uiDegrade.ts
=> feat: 兼容低版本火狐浏览器sticky定位布局

components/table/pipeline/features/rowDrag.tsx
=> fix: 优化行拖拽触发逻辑，避免点击时也触发行拖拽

components/table/utils/browserType.tsx
=> feat: 兼容低版本IE11 sticky定位布局

components/table/base/header.tsx
=> fix: 修复表格IE下右侧固定样式失效的问题

components/table/base/globalStyleComponent.tsx, components/table/base/styles.ts, components/table/base/table.tsx, components/table/interfaces.ts, components/table/pipeline/const.ts, components/table/pipeline/features/featureApi/RowDragApi.ts, components/table/pipeline/features/featureApi/utils.ts, components/table/pipeline/features/rowDrag.tsx, components/table/pipeline/features/treeMode.tsx, components/table/pipeline/pipeline.ts
=> feat: 表格行拖拽功能支持跨表拖拽

components/table/base/styles.ts, components/table/interfaces.ts, components/table/pipeline/features/rowDrag.tsx, components/table/pipeline/features/treeMode.tsx
=> feat:行拖拽增加公共参数和树型表格悬停展开逻辑

components/table/base/styles.ts, components/table/pipeline/features/rowDrag.tsx
=> feat:跨表行拖拽第二个表是空数据时也支持拖拽

components/table/pipeline/features/rowDrag.tsx
=> fix: 行拖拽拖拽到tableBody时，拖拽指示线位置没有更新

components/table/base/styles.ts, components/table/pipeline/features/rowDrag.tsx
=> fix: 行拖拽调整悬停滚动速度 && 折叠展开行回调放到dragstop后执行

components/table/pipeline/features/rowDrag.tsx
=> fix:表格拖拽指示线样式跟随拖拽进入的表格显示

components/table/base/styles.ts
=> fix: 修复右冻结滚动时表头有内容漏出的问题

components/table/base/globalStyleComponent.tsx, components/table/base/header.tsx, components/table/base/html-table.tsx, components/table/base/interfaces.tsx, components/table/base/styles.ts, components/table/base/table.tsx, components/table/base/utils.tsx, components/table/pipeline/features/colGroupExtendable.tsx, components/table/pipeline/features/columnDrag.tsx, components/table/pipeline/features/columnFilter.tsx, components/table/pipeline/features/columnResizeWidth.tsx, components/table/pipeline/features/contextMenu.tsx, components/table/pipeline/features/filter/Filter.tsx, components/table/pipeline/features/filter/FilterPanel.tsx, components/table/pipeline/features/rowDrag.tsx, components/table/pipeline/features/tips.tsx, components/table/pivot/cross-table/interfaces.ts, components/table/utils/element.ts
=> Revert "rtl样式适配"
